name: E2E testing for EC-CUBE
run-name: E2E testing for EC-CUBE

on:
  workflow_call:
jobs:
  run-on-linux:
    name: Run on Linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pattern:
          - 'test:e2e'
        group:
          - 'test/front_guest'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup environment
      run: echo "COMPOSE_FILE=docker-compose.yml:docker-compose.pgsql.yml:docker-compose.dev.yml:docker-compose.owaspzap.yml:docker-compose.owaspzap.daemon.yml" >> $GITHUB_ENV

